version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: artist-db
    environment:
      POSTGRES_DB: artistdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: artist-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"

  api:
    build: .
    container_name: artist-api
    depends_on:
      - postgres
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/artistdb
      MINIO_URL: http://minio:9000
    ports:
      - "8080:8080"
